### ISSUE TITLE
Feature request: Dialog by instanceOf not just tag.

### ISSUE THREAD

**Issue by neiljaywarner** [chiuki/espresso-samples#1]
Hello,
What do you think of a idling resource that you could use for all your espresso tests that checks
        getFragmentManager().getFragments() and iterates through seeing if any of them are LoadingDialogFragment - rather than having to register and unregister before every time a spinner pops up, just register in before and unregister in after?

Since any spinner means the app is not idle, rather than a specific spinner?

**Comment by chiuki** [comment]
Sure! Fork this repo and implement that as a solution, post the link to this issue, and I'll link to it from the README.
