### ISSUE TITLE
How to understand the default synchronization function of Espresso

### ISSUE THREAD

**Issue by wangyuebanzi** [chiuki/espresso-samples#4]
Hello,I see the following content written on your blog
![2017-08-01 9 30 48](https://user-images.githubusercontent.com/30208125/28805662-3a4f2c6a-769e-11e7-9586-f128a6c0e80a.png)
How to understand the default synchronization function of Espresso
for example ,I use Handler send a message to UI thread ,  is there a UI event in the current message queue? 
And what is the default AsyncTask thread pool meaning(use the class of AsyncTask in your app)?  
Looking forward to your answer @chiuki   thanks

**Comment by chiuki** [comment]
Out of scope for this project
