### ISSUE TITLE
ElapsedTimeIdlingResource no longer works with the new Espresso IdlingRegistry.

### ISSUE THREAD

**Issue by mijiapps** [chiuki/espresso-samples#7]
The former Espresso.registerIdlingResources() method has been deprecated in favor of using the new IdlingRegistry via getInstance().register(). However, after upgrading, my test no longer work using the ElapsedTimeIdlingResource. 

```
        mElapsedTimeIdlingResource = new ElapsedTimeIdlingResource(3);
        getInstance().register(mElapsedTimeIdlingResource);
       // Do Something
        getInstance().unregister(mElapsedTimeIdlingResource);
```

**Comment by chiuki** [comment]
I've updated the `idling-resource-elapsed-time` sample to register with `IdlingRegistry.getInstance()` and verified that the tests pass.
